### ISSUE TITLE
Dyntaxa data flow from IPT

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/dyntaxa#6]
- set up data flow so that Dyntaxa is being published from our shared instance of IPT currently at http://www.gbif.se/ipt/ rather than directly from https://api.artdatabanken.se/taxonservice/v1/DarwinCore/DarwinCoreArchiveFile?Subscription-Key=4b068709e7f2427d9fc76bf42d8e2b57

- have metadata curation happen at the IPT instance

**Comment by ronquist** [comment]
We need to discuss this solution in ExO. Still unclear whether we can channel DynTaxa through the shared IPT instance.

**Comment by mskyttner** [comment]
When you write "can" do you mean whether it is technically possible or whether it is strategically preferred? 

In the latest TC meetings, @Adbmnk and others in the TC meeting have been working towards flowing this data via IPT.

**Comment by ronquist** [comment]
Great that you are already making progress on this! This would be the preferred way, if you ask me, although I think Holger wanted to discuss the strategic implications before we finalize this discussion at the ExO level. Do you see any concerns for Artdatabanken in publishing the DwC-A through the common Swedish IPT worth discussing by ExO?

**Comment by mskyttner** [comment]
Since 2012 the data flow went over the IPT and I thought there was agreement in reestablishing this data flow, both in the ExO and the TC, for reasons discussed during the autumn and spring.

I am not aware of any new or previously unknown concerns beyond what has been discussed earlier with @holgerdettki, and assumed there are some developments happened in the last few days that changes the situation when learning that this needs to be discussed again in the ExO.

**Comment by ronquist** [comment]
No developments as far as I know, just a need to make sure that everyone in the ExO is up to date and on board with what is happening.

**Comment by holgerdettki** [comment]
Talked to Martin K @Adbmnk to get an update on the current and planned data flow of Dyntaxa data to GBIF. No changes needed right now to the planned tasks above. However, as the dataflow 'Dyntaxa API->DwC-A->Script to something something-> Read into IPT->DwC-A with versioning' might not be the most straight forward way to go, this is something we can discuss for the next 'version' in the future. But for now - just do it as planned.
On a personal note as a programmer I am curious how the check if there is a new Dyntaxa-DwC-A file is supposed to work. Markus & I can discuss this seperately

**Comment by ronquist** [comment]
Sounds good to me. I talked briefly to Manash about pushing and pulling versions of DynTaxa to IPT and it seems we can find a better solution on this than what we will have in the first version. Also note parallel work on taxonomy merging for molecular data to improve taxonomic indexing of Swedish LA instance. I have encouraged Maria Prager and Anders A to start a separate project for this so all of us can follow their progress on taxonomy merging shortly, I hope.

I will move this issue now to in progress and assign it to @Adbmnk .

**Comment by ronquist** [comment]
Apparently I do not have privileges to assign issues to people. Can @mskyttner assign it to @Adbmnk if this is OK to both of you? We can discuss who should be assigning issues to people in the future; maybe that right should be restricted to TC members and not involve anyone in ExO.

**Comment by ronquist** [comment]
I am closing this issue and starting a new one for discussing future implementations of DynTaxa and other dataflows through IPT in SBDI.
